version: "3.1"

services:

  mysql-crypto:
    container_name: mysql-crypto
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: crypto_notifier
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - default


networks: 
  default:
    driver: bridge    